--drop view vactivestudents;
--drop view vallgrades;
--drop view vclasstrack;
--drop view  vgrades;
--drop view vinactivestudents;
--drop view  vmajors;
--drop view  vstudents;
--drop view  vyears ;

drop table Resume;
drop table Employee;
drop table Store;
drop table Product;
drop table Supplier;
drop table Customer;
drop table Orders;
drop table Place_order;
drop table Orderstat;
drop table Game;
drop table Console;
drop table Controller;